/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DropdownMenu: typeof import('./src/components/DropdownMenu.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    StaticAsync: typeof import('./src/components/staticAsync.vue')['default']
    Virtual: typeof import('./src/components/Virtual.vue')['default']
    WebSocket: typeof import('./src/components/WebSocket.vue')['default']
  }
}
